### ISSUE TITLE
Rename to parity-rocksdb and publish to crates

### ISSUE THREAD

**Issue by dvdplm** [paritytech/rust-rocksdb#16]
If we're not going to try to upstream the changes in this fork I think we should rename it so we can publish it to crates.

**Comment by andresilva** [comment]
And also update the README while we're at it.

**Comment by dvdplm** [comment]
This is needed to publish `kvdb-rocksdb` which is blocking https://github.com/paritytech/parity-ethereum/pull/9410

**Comment by andresilva** [comment]
Fixed in #18.
